src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Russia</fullName>
    </customValue>
    <customValue>
        <fullName>Slovenia</fullName>
    </customValue>
    <customValue>
        <fullName>Uganda</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/HS_RestCountrySet.cls
/**
 * Created by jakub.urbanek on 09.05.2022.
 */
@RestResource(UrlMapping='/GetCountry/*')
global class HS_RestCountrySet {

    @HttpGet
    global static List<String> getCountryGlobalSet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        SObjectField picklistUsingGlobal = SObjectType.Doctor__c.fields.Country__c.getSObjectField();

        List<PicklistEntry> entries = picklistUsingGlobal.getDescribe().getPicklistValues();
        List<String> countriesAsString = new List<String>();
        for (Schema.PicklistEntry objPickList : entries) {
            countriesAsString.add(objPickList.getValue());
        }
        return countriesAsString;
    }
}