src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Of_Birth__c</fullName>
        <label>Date Of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImgURL__c</fullName>
        <label>ImgURL</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Professional_Title__c</fullName>
        <label>Professional Title</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>lek. med.</fullName>
                </value>
                <value>
                    <fullName>lek. stom.</fullName>
                </value>
                <value>
                    <fullName>dr n. med.</fullName>
                </value>
                <value>
                    <fullName>prof. dr hab. n. med.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Specialization__c</fullName>
        <label>Specialization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cardiologist</fullName>
                </value>
                <value>
                    <fullName>Gynecologist</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Dietician</fullName>
                </value>
                <value>
                    <fullName>Neurologist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Hospital__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Hospital_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <formula>AND(
Start_Date__c &lt;= TODAY(),
 OR(
  Expiration_Date__c &gt;= TODAY(),
  ISBLANK(Expiration_Date__c )
 )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Hospital Contracts</relationshipLabel>
        <relationshipName>Hospital_Contracts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hospital__c</fullName>
        <label>Hospital</label>
        <referenceTo>Hospital__c</referenceTo>
        <relationshipLabel>Hospital Contracts</relationshipLabel>
        <relationshipName>Hospital_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Hospital Contract</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Hospital Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hospital Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Russia</fullName>
    </customValue>
    <customValue>
        <fullName>Slovenia</fullName>
    </customValue>
    <customValue>
        <fullName>Uganda</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/DoctorDetailsController.cls
/**
 * Created by hubert.bogusz on 11.04.2022.
 */

public with sharing class DoctorDetailsController {
    public Doctor__c doctor { get; set; }
    public Hospital_Contract__c contract { get; set; }
    public Hospital__c hospital { get; set; }
    public HospitalWrapper hospitalWrapper { get; set; }
    public HospitalWrapper searchWrapper { get; set; }
    public List<Hospital__c> hospitalsFromQuery { get; set; }
    public List<HospitalWrapper> hospitals { get; set; }
    private List<String> conditions = new List<String>();
    public String hospitalName { get; set; }
    public boolean isDisable { get; set; }
    public Id hospitalId { get; set; }
    public PageReference pageReference { get; set; }
    public Blob fileBody { get; set; }
    public String fileName { get; set; }
    public String imageUrl { get; set; }



    public DoctorDetailsController(ApexPages.StandardController standardController) {
        hospitalWrapper = new HospitalWrapper();
        searchWrapper = new HospitalWrapper();
        hospitals = new List<HospitalWrapper>();
        contract = new Hospital_Contract__c();
        pageReference = ApexPages.currentPage();
        isDisable = true;
        String doctorId = standardController.getId();
        if (String.isBlank(doctorId)) {
            doctor = new Doctor__c();
        } else {
            doctor = [
                    SELECT Professional_Title__c,Email__c,First_Name__c,
                            Phone__c,Name,Date_Of_Birth__c,Specialization__c, Country__c,City__c,
                            Street__c, Postal_Code__c,ImgURL__c, CreatedBy.Name,CreatedBy.CreatedDate, LastModifiedBy.Name,
                            LastModifiedBy.CreatedDate, (
                            SELECT Hospital__r.Name, Start_Date__c, Expiration_Date__c, Active__c
                            FROM Hospital_Contracts__r
                    )
                    FROM Doctor__c
                    WHERE Id = :doctorId
            ];
        }
    }

    public PageReference searchHospitals(){
        if (hospitals.size() > 0) {
            hospitals.clear();
        }
        String query =' SELECT Id, Name, Email__c, Country__c FROM Hospital__c WHERE Name LIKE '
                + '\'%' + searchWrapper.hospital.Name + '%\'' ;
        System.debug('hospital name : ' + searchWrapper.hospital.Name);
        conditions.clear();
        if (String.isNotBlank(searchWrapper.hospital.Email__c)) {
            conditions.add('Email__c LIKE ' + '\'%' + searchWrapper.hospital.Email__c + '%\'');
        }
        if (String.isNotBlank(searchWrapper.hospital.Country__c)) {
            conditions.add('Country__c LIKE' + '\'' + searchWrapper.hospital.Country__c + '%\'');
        }

        if (conditions.size() > 0) {
//            query += String.join(conditions, ' AND ');
            for (Integer i = 0; i < conditions.size(); i++) {
                query += ' AND ' + conditions[i];
            }
        }
        hospitalsFromQuery = Database.query(query);
        for(Hospital__c hospital: hospitalsFromQuery){
            HospitalWrapper hospitalWrapper = new HospitalWrapper();
            hospitalWrapper.hospital = hospital;
            hospitals.add(hospitalWrapper);
        }
        if (hospitals.isEmpty()) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'There-s no records with provided criteria'));
        }
        return null;
    }
    public void clearFields() {
        if (searchWrapper.hospital != null) {
            searchWrapper.hospital.clear();
        }
        if (hospitals != null) {
            hospitals.clear();
        }
        isDisable=true;
    }
    public void showInfo(){
        for (HospitalWrapper wrapper : hospitals){
            if(wrapper.hospital.id == hospitalId){
                hospitalWrapper = wrapper;
                wrapper.isSelected = true;
            }
            else {
                wrapper.isSelected = false;
            }
        }
    }
    public PageReference saveContract() {
        try {
            contract.Hospital__c = hospitalWrapper.hospital.Id;
            contract.Doctor__c = doctor.Id;
            insert contract;
            pageReference.setRedirect(true);
            return pageReference;
        } catch (exception e) {
            ApexPages.addMessages(e);
            return null;
        }
    }
    public void checkDisableClear(){
        if ( hospitals.size() > 0 || String.isNotBlank(searchWrapper.hospital.Name)
                || String.isNotBlank(searchWrapper.hospital.Email__c) || String.isNotBlank(searchWrapper.hospital.Country__c)) {
            isDisable = false;
        } else {
            isDisable = true;
        }
    }

    public void addImage(){
       try{
           doctor.ImgURL__c = imageUrl;
           System.debug(imageUrl);
           update doctor;
       }
       catch(exception e) {
           ApexPages.addMessages(e);
           System.debug('error');
       }
    }

    public PageReference refreshHiddenInput(){
        System.debug('imageUrl: ' + imageUrl);
        return null;
    }
}