src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Hospital__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Opening_Date__c</fullName>
        <label>Opening Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Hospital_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <formula>AND(
Start_Date__c &lt;= TODAY(),
 OR(
  Expiration_Date__c &gt;= TODAY(),
  ISBLANK(Expiration_Date__c )
 )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Hospital Contracts</relationshipLabel>
        <relationshipName>Hospital_Contracts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hospital__c</fullName>
        <label>Hospital</label>
        <referenceTo>Hospital__c</referenceTo>
        <relationshipLabel>Hospital Contracts</relationshipLabel>
        <relationshipName>Hospital_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Hospital Contract</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Hospital Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hospital Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Russia</fullName>
    </customValue>
    <customValue>
        <fullName>Slovenia</fullName>
    </customValue>
    <customValue>
        <fullName>Uganda</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/HospitalDetailController.cls
/**
 * Created by hubert.bogusz on 12.04.2022.
 */

public with sharing class HospitalDetailController {
    public Hospital__c hospital { get; set; }
    public Hospital_Contract__c contract { get; set; }
    public HospitalWrapper hospitalWrapper { get; set; }
    public HospitalDetailController(ApexPages.StandardController standardController) {
        hospitalWrapper = new HospitalWrapper();
        String hospitalId = standardController.getId();
        if (String.isBlank(hospitalId)) {
            hospitalWrapper = new HospitalWrapper();
        } else {
            hospitalWrapper.hospital = [
                    SELECT Name, Email__c, Phone__c, Opening_Date__c, Country__c, City__c, Street__c, Postal_Code__c, CreatedBy.Name,CreatedBy.CreatedDate, LastModifiedBy.Name,
                            LastModifiedBy.CreatedDate, (
                            SELECT Doctor__r.First_Name__c, Doctor__r.Name, Start_Date__c, Expiration_Date__c, Active__c
                            FROM Hospital_Contracts__r
                    )
                    FROM Hospital__c
                    WHERE Id = :hospitalId
            ];
            if(hospitalWrapper.hospital.City__c == 'New York'){
                hospitalWrapper.latitude = 40.716941;
                hospitalWrapper.longitude = -74.008185;
            } else if(hospitalWrapper.hospital.City__c == 'Lublin'){
                    hospitalWrapper.latitude = 51.247455;
                    hospitalWrapper.longitude = 22.565162;
                }
        }
    }
}