src/objects/Hospital__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Russia</fullName>
    </customValue>
    <customValue>
        <fullName>Slovenia</fullName>
    </customValue>
    <customValue>
        <fullName>Uganda</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/RESTHospitalService.cls
/**
 * Created by hubert.bogusz on 10.05.2022.
 */

    @RestResource(urlMapping='/Hospitals/*')
    global with sharing class RESTHospitalService {
        private static final String ERROR = 'error';
        private static final String SUCCESS = 'successful';
        @HttpGet
        global static List<RESTWrappers.HospitalRESTWrapper> getWorkshops() {
            RestRequest request = RestContext.request;
            String workshopId = request.requestURI.substring(request.requestURI.lastIndexOf('/') + 1);
            String nameParam = request.params.get('name') + '%';
            String countryParam = request.params.get('country') + '%';
            List<RESTWrappers.HospitalRESTWrapper> hospitalRESTWrapper = new List<RESTWrappers.HospitalRESTWrapper>();
            List <Hospital__c> hospitals  = [ SELECT Id, Name, Country__c, City__C, Street__c, Phone__c, Email__c
            FROM Hospital__c
            WHERE Name LIKE :nameParam AND Country__c LIKE :countryParam
            ];
            for (Hospital__c hospital : hospitals){
                hospitalRESTWrapper.add(convertHospitalToWrapper(hospital));
            }

            return hospitalRESTWrapper;
        }
        @HttpPost
        global static RESTWrappers.HospitalsResponse createHospital() {
            RestRequest request = RestContext.request;
            RestResponse restResponse = RestContext.response;
            String requestString = request.requestBody.toString();

            RESTWrappers.HospitalRESTWrapper hospitalRESTWrapper = (RESTWrappers.HospitalRESTWrapper) JSON.deserialize(requestString, RESTWrappers.HospitalRESTWrapper.class);
            RESTWrappers.HospitalsResponse response = new RESTWrappers.HospitalsResponse();
            Hospital__c hospital = new Hospital__c();
            hospital = convertWrapperToHospital(hospitalRESTWrapper);

            try {
                insert hospital;
                response.status = SUCCESS;
                response.addedHospital = hospital;
            } catch (Exception e) {
                response.status = ERROR;
                response.errorMessage = e.getMessage();
                return response;
            }
            return response;
        }


        private static Hospital__c convertWrapperToHospital(RESTWrappers.HospitalRESTWrapper wrapper){
            Hospital__c hospital = new Hospital__c(
                    Name = wrapper.name,
                    City__c = wrapper.city,
                    Country__c = wrapper.country,
                    Email__c = wrapper.email,
                    Phone__c = wrapper.phone,
                    Street__c = wrapper.street
            );
            return hospital;
        }

        private static RESTWrappers.HospitalRESTWrapper convertHospitalToWrapper(Hospital__c hospital) {
            RESTWrappers.HospitalRESTWrapper hospitalRESTWrapper = new RESTWrappers.HospitalRESTWrapper();
            hospitalRESTWrapper.name = hospital.Name;
            hospitalRESTWrapper.city = hospital.City__c;
            hospitalRESTWrapper.country = hospital.Country__c;
            hospitalRESTWrapper.phone = hospital.Phone__c;
            hospitalRESTWrapper.street = hospital.Street__c;
            hospitalRESTWrapper.email = hospital.Email__c;
            return hospitalRESTWrapper;
        }

    }