src/objects/Hospital__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LogHandler__c.object
<CustomObject>
    <fields>
        <fullName>Attempt_Number__c</fullName>
        <label>Attempt Number</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Create_Date__c</fullName>
        <label>Create Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_body__c</fullName>
        <label>Request body</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_endpoint__c</fullName>
        <label>Request endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_body__c</fullName>
        <label>Response body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_status_code__c</fullName>
        <label>Response status code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LogHandler</label>
    <nameField>
        <label>Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LogHandlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Russia</fullName>
    </customValue>
    <customValue>
        <fullName>Slovenia</fullName>
    </customValue>
    <customValue>
        <fullName>Uganda</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/HospitalCalloutHandler.cls
/**
 * Created by hubert.bogusz on 10.05.2022.
 */

public with sharing class HospitalCalloutHandler {
    public String createResponseStatus { get; set; }

    public LogHandler__c createHospital(List<Hospital__c> newHospitals) {
        string endPoint = 'https://empathetic-shark-tza12g-dev-ed.my.salesforce.com/services/apexrest/Hospitals';
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        String accessToken = AuthorizeClass.getRequestToken();
        System.debug('accessToken: ' + accessToken);
        request.setHeader('Authorization', 'Bearer ' + accessToken);
        request.setHeader('Content-Type', 'application/json');
        request.setMethod('POST');
        request.setEndpoint(endPoint);
        request.setBody(JSON.serialize(convertHospitalToWrapper(newHospitals.get(0))));
        System.debug('Hospital: ' + newHospitals.get(0));
        HttpResponse httpResponse = http.send(request);
        createResponseStatus = String.valueOf(httpResponse.getStatusCode());
        System.debug('Created done');
        return createLog(request, httpResponse, 'Hospital');
    }

    private static Hospital__c convertWrapperToHospital(RESTWrappers.HospitalRESTWrapper wrapper) {
        Hospital__c hospital = new Hospital__c(
                Name = wrapper.name,
                City__c = wrapper.city,
                Country__c = wrapper.country,
                Email__c = wrapper.email,
                Phone__c = wrapper.phone,
                Street__c = wrapper.street
        );
        return hospital;
    }

    private static RESTWrappers.HospitalRESTWrapper convertHospitalToWrapper(Hospital__c hospital) {
        RESTWrappers.HospitalRESTWrapper hospitalRESTWrapper = new RESTWrappers.HospitalRESTWrapper();
        hospitalRESTWrapper.id = hospital.id;
        hospitalRESTWrapper.name = hospital.Name;
        hospitalRESTWrapper.city = hospital.City__c;
        hospitalRESTWrapper.country = hospital.Country__c;
        hospitalRESTWrapper.phone = hospital.Phone__c;
        hospitalRESTWrapper.street = hospital.Street__c;
        hospitalRESTWrapper.email = hospital.Email__c;
        return hospitalRESTWrapper;
    }

    public static LogHandler__c createLog(HttpRequest request, HttpResponse response, String objectName) {

        LogHandler__c logHandler = new LogHandler__c();

        logHandler.Request_body__c = request.getBody();
        logHandler.Request_endpoint__c = request.getEndpoint();
        logHandler.Response_status_code__c = String.valueOf(response.getStatusCode());
        logHandler.Response_body__c = String.valueOf(JSON.deserializeUntyped(response.getBody()));
        logHandler.Status__c = response.getStatus();
        logHandler.Create_Date__c = Date.today();
        logHandler.Attempt_Number__c = 1;
        logHandler.Object__c = objectName;

        insert logHandler;
        return logHandler;

    }
}