src/objects/Hospital__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Russia</fullName>
    </customValue>
    <customValue>
        <fullName>Slovenia</fullName>
    </customValue>
    <customValue>
        <fullName>Uganda</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/HS_RestIntegrationHospital.cls
@RestResource(UrlMapping='/TriggerCalloutsHospital/*')
global class HS_RestIntegrationHospital {

    @HttpPost
    global static String createNewHospital() {

        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        String jsonString = req.requestBody.toString();
        List<responseWrapper> wResps = (List<responseWrapper>) JSON.deserialize(jsonString, List<responseWrapper>.class);
        List<Hospital__c> hospitals = new List<Hospital__c>();

        for (responseWrapper wResp : wResps) {
            Hospital__c hospital = new Hospital__c();
            hospital.Name = wResp.name;
            hospital.Country__c = wResp.Country;
            hospital.External_Id__c = wResp.id;  

            hospitals.add(hospital);
        }

        try {
            System.debug('tryHospital');
            Database.insert(hospitals);
        }catch (DMLException e){
            System.debug(e);
        }


        return 'Success';
    }

    global class responseWrapper {
        global String id { get; set; }
        global String name { get; set; }
        global String Country { get ; set; }
        global String ExternalId {get; set;}
    }


}